// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RouteRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteRequest) Reset()         { *m = RouteRequest{} }
func (m *RouteRequest) String() string { return proto.CompactTextString(m) }
func (*RouteRequest) ProtoMessage()    {}
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_f7cf8cd9a8b67dbd, []int{0}
}
func (m *RouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteRequest.Unmarshal(m, b)
}
func (m *RouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteRequest.Marshal(b, m, deterministic)
}
func (dst *RouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteRequest.Merge(dst, src)
}
func (m *RouteRequest) XXX_Size() int {
	return xxx_messageInfo_RouteRequest.Size(m)
}
func (m *RouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteRequest proto.InternalMessageInfo

func (m *RouteRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RouteRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *RouteRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type RouteResponse struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary" json:"summary,omitempty"`
	StationTravelled     int64    `protobuf:"varint,2,opt,name=station_travelled,json=stationTravelled" json:"station_travelled,omitempty"`
	Route                []string `protobuf:"bytes,3,rep,name=route" json:"route,omitempty"`
	TravelTime           string   `protobuf:"bytes,4,opt,name=travel_time,json=travelTime" json:"travel_time,omitempty"`
	Instruction          string   `protobuf:"bytes,5,opt,name=instruction" json:"instruction,omitempty"`
	QueryTime            string   `protobuf:"bytes,6,opt,name=query_time,json=queryTime" json:"query_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteResponse) Reset()         { *m = RouteResponse{} }
func (m *RouteResponse) String() string { return proto.CompactTextString(m) }
func (*RouteResponse) ProtoMessage()    {}
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_f7cf8cd9a8b67dbd, []int{1}
}
func (m *RouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteResponse.Unmarshal(m, b)
}
func (m *RouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteResponse.Marshal(b, m, deterministic)
}
func (dst *RouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteResponse.Merge(dst, src)
}
func (m *RouteResponse) XXX_Size() int {
	return xxx_messageInfo_RouteResponse.Size(m)
}
func (m *RouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteResponse proto.InternalMessageInfo

func (m *RouteResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *RouteResponse) GetStationTravelled() int64 {
	if m != nil {
		return m.StationTravelled
	}
	return 0
}

func (m *RouteResponse) GetRoute() []string {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *RouteResponse) GetTravelTime() string {
	if m != nil {
		return m.TravelTime
	}
	return ""
}

func (m *RouteResponse) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *RouteResponse) GetQueryTime() string {
	if m != nil {
		return m.QueryTime
	}
	return ""
}

func init() {
	proto.RegisterType((*RouteRequest)(nil), "pb.RouteRequest")
	proto.RegisterType((*RouteResponse)(nil), "pb.RouteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RouteService service

type RouteServiceClient interface {
	GetRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
}

type routeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRouteServiceClient(cc *grpc.ClientConn) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) GetRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	out := new(RouteResponse)
	err := grpc.Invoke(ctx, "/pb.RouteService/GetRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RouteService service

type RouteServiceServer interface {
	GetRoute(context.Context, *RouteRequest) (*RouteResponse, error)
}

func RegisterRouteServiceServer(s *grpc.Server, srv RouteServiceServer) {
	s.RegisterService(&_RouteService_serviceDesc, srv)
}

func _RouteService_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RouteService/GetRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetRoute(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoute",
			Handler:    _RouteService_GetRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route.proto",
}

func init() { proto.RegisterFile("route.proto", fileDescriptor_route_f7cf8cd9a8b67dbd) }

var fileDescriptor_route_f7cf8cd9a8b67dbd = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0x69, 0xd2, 0xe6, 0xdf, 0x4c, 0xfe, 0x96, 0x76, 0xf0, 0xb0, 0x14, 0xc5, 0x90, 0x53,
	0x41, 0x48, 0x40, 0x1f, 0xc0, 0x9b, 0x1e, 0x85, 0xd8, 0x7b, 0x49, 0xea, 0x58, 0x16, 0x92, 0x6c,
	0xba, 0xbb, 0x29, 0xf4, 0xea, 0x2b, 0xf8, 0x5e, 0x5e, 0x7c, 0x05, 0x1f, 0x44, 0x32, 0x9b, 0x42,
	0x6e, 0x33, 0xbf, 0xfd, 0xe6, 0xdb, 0x99, 0x0f, 0x22, 0xad, 0x3a, 0x4b, 0x69, 0xab, 0x95, 0x55,
	0xe8, 0xb5, 0xe5, 0xfa, 0xe6, 0xa0, 0xd4, 0xa1, 0xa2, 0xac, 0x68, 0x65, 0x56, 0x34, 0x8d, 0xb2,
	0x85, 0x95, 0xaa, 0x31, 0x4e, 0x91, 0x3c, 0xc3, 0xff, 0xbc, 0x1f, 0xc8, 0xe9, 0xd8, 0x91, 0xb1,
	0x88, 0x30, 0xfd, 0xd0, 0xaa, 0x16, 0x93, 0x78, 0xb2, 0x09, 0x73, 0xae, 0x71, 0x01, 0x9e, 0x55,
	0xc2, 0x63, 0xe2, 0x59, 0xd5, 0x6b, 0xac, 0xac, 0x49, 0xf8, 0x4e, 0xd3, 0xd7, 0xc9, 0xf7, 0x04,
	0xae, 0x06, 0x23, 0xd3, 0xaa, 0xc6, 0x10, 0x0a, 0xf8, 0x67, 0xba, 0xba, 0x2e, 0xf4, 0x79, 0x30,
	0xbb, 0xb4, 0x78, 0x0f, 0x2b, 0xe3, 0xb6, 0xd8, 0x59, 0x5d, 0x9c, 0xa8, 0xaa, 0xe8, 0x9d, 0xed,
	0xfd, 0x7c, 0x39, 0x3c, 0x6c, 0x2f, 0x1c, 0xaf, 0x61, 0xc6, 0x17, 0x09, 0x3f, 0xf6, 0x37, 0x61,
	0xee, 0x1a, 0xbc, 0x83, 0xc8, 0x8d, 0xee, 0x78, 0x93, 0x29, 0x7f, 0x00, 0x0e, 0x6d, 0x65, 0x4d,
	0x18, 0x43, 0x24, 0x1b, 0x63, 0x75, 0xb7, 0xef, 0xed, 0xc4, 0x8c, 0x05, 0x63, 0x84, 0xb7, 0x00,
	0xc7, 0x8e, 0xf4, 0xd9, 0x39, 0x04, 0x2c, 0x08, 0x99, 0xf4, 0x06, 0x0f, 0xaf, 0x43, 0x30, 0x6f,
	0xa4, 0x4f, 0x72, 0x4f, 0xf8, 0x04, 0xf3, 0x17, 0xb2, 0x8c, 0x70, 0x99, 0xb6, 0x65, 0x3a, 0x8e,
	0x6d, 0xbd, 0x1a, 0x11, 0x77, 0x7f, 0xb2, 0xf8, 0xfc, 0xf9, 0xfd, 0xf2, 0xe6, 0x18, 0x64, 0xbc,
	0x72, 0x19, 0x70, 0xe0, 0x8f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x51, 0x68, 0x58, 0xa1,
	0x01, 0x00, 0x00,
}
